DATASETS:
  TRAIN: ("waste_train",)
  TEST: ("waste_test",)
DATALOADER:
  NUM_WORKERS: 4
MODEL:
  # RPN:
  #   POST_NMS_TOPK_TRAIN: 2000
  #   PRE_NMS_TOPK_TRAIN: 2000
  # WEIGHTS: None
  # BACKBONE:
  #   NAME: 'MyPersonalBackbone'
  #   IN_CHANNELS: 3
  #   NUM_CLASSES: 3
  #   TYPE: 'resnet50_pretrained'
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512 
    NUM_CLASSES: 4 
  SEM_SEG_HEAD:
    NUM_CLASSES: 4
  RETINANET:
    NUM_CLASSES: 4
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00025  # pick a good LR
  MAX_ITER: 2000    # 300 iterations seems good enough for this toy dataset; you will need to train longer for a practical dataset
  STEPS: []        # do not decay learning rate
TEST:
  EVAL_PERIOD: 100

